### ISSUE TITLE
ERROR: Cannot find the fakeroot binary. (lib32-libexif)

### ISSUE THREAD

**Issue by KweezyCode** [Troplo/office-install.sh#2]
==> Build package lib32-libexif 0.6.24-1 (Sep 19 May 2024 17:11:32)
==> Check dependencies to run...
==> Checking dependencies to build...
==> Retrieving source files...
  -> Found libexif-0_6_24-release.tar.gz
==> Checking the source files using sha512sums...
    libexif-0_6_24-release.tar.gz ... Done
==> Deleting the '$srcdir/' directory ...
==> Extracting the source files...
  -> Extracting 'libexif-0_6_24-release.tar.gz' with bsdtar
==> Source files are ready.
==> ERROR: Cannot find the fakeroot binary.

**Comment by KweezyCode** [comment]
Manjaro Latest (VirtualBox clean image)

**Comment by KweezyCode** [comment]
(it requires automake, autoconf, fakeroot, make, gcc)

**Comment by Troplo** [comment]
Thanks, I added a check for either yay and paru, and if neither are found it requests that the user installs them.
