### ISSUE TITLE
Office icons are broken

### ISSUE THREAD

**Issue by KweezyCode** [Troplo/office-install.sh#3]
![image](https://github.com/Troplo/office-install.sh/assets/36813920/332fbeee-a619-4d80-8108-fc0c6d24817c)

Manjaro Latest (KDE 6)

**Comment by Troplo** [comment]
Added, it will now download a set of icons and use them for the .desktop file. You can pick option 8 to reinstall the .desktop files without reinstalling Office, may need to manually refresh the KDE icon cache in the KDE Menu Editor application > Save button (it should do this automatically but sometimes it doesn't.)
